### ISSUE TITLE
Неинформативно

### ISSUE THREAD

**Issue by KomarDL** [katyalys/OSISP#2]
https://github.com/katyalys/OSISP/blob/96a8ed3d59d54d3ce6707daaa0169745cbe6403f/1.6.sh#L3
https://github.com/katyalys/OSISP/blob/96a8ed3d59d54d3ce6707daaa0169745cbe6403f/1.6.sh#L8

Сообщения об ошибках не дают понять как использовать скрипт

**Comment by katyalys** [comment]
исправлено
