### ISSUE TITLE
Неинформативно

### ISSUE THREAD

**Issue by KomarDL** [katyalys/OSISP#3]
https://github.com/katyalys/OSISP/blob/96a8ed3d59d54d3ce6707daaa0169745cbe6403f/laba1.sh#L4
https://github.com/katyalys/OSISP/blob/96a8ed3d59d54d3ce6707daaa0169745cbe6403f/laba1.sh#L16

Сообщения об ошибках не позволяют понять как использовать скрипт

**Comment by katyalys** [comment]
исправлено
